#!name =  iRingo: 🌤 WeatherKit
#!desc = iOS 18 & macOS 15 & watchOS 11\n1.解锁全部天气功能\n2.替换空气质量数据\n3.添加下一小时降水数据

#[rewrite_local]
^https?:\/\/weatherkit\.apple\.com\/api\/v1\/availability\/ url script-response-body https://github.com/NSRingo/WeatherKit/releases/download/v1.8.17/response.bundle.js
^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/ url script-response-body https://github.com/NSRingo/WeatherKit/releases/download/v1.8.17/response.bundle.js
^https?:\/\/weather-analytics-events\.apple\.com\/ url reject

#[mitm]
hostname = weatherkit.apple.com, weather-analytics-events.apple.com, *.tthr.apple.com
